# docker compose to build the micro services

version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"

      
  ponder:
    build:
      context: ./ponder
      dockerfile: Dockerfile
    ports:
      - "8000:42069"