version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

    environment:
      - PONDER_API_URL=http://ponder:42069

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
      
  ponder:
    build:
      context: ./ponder
      dockerfile: Dockerfile
    ports:
    - "42069:42069"
    volumes:
    - ./data/ponder:/app/.ponder
    extra_hosts:
      - "host.docker.internal:host-gateway"