agent_name: goldman_stacked
author: zarathustra
version: 0.1.0
license: Apache-2.0
description: Agent to compete in EthPrague 2024 hackathon, represents a member of
  the AI investment council who protect DAO`s from governance attacks.
aea_version: '>=1.55.0, <2.0.0'
fingerprint:
  __init__.py: bafybeici47yy5bccv5pvkljcgqvmkvs5nq3nu2jf2escld3qwmpqxhmh6u
  tests/__init__.py: bafybeibk76alseqt3ufreyev7rnz5zuk6dcftt7c2ob54gmhpt6xrhkg2y
  tests/test_agent.py: bafybeiei2ipqhyzyth4jgcrw6y6omhh5kddutntxlr6ejo7coipt3obt4q
fingerprint_ignore_patterns: []
connections:
- eightballer/http_client:0.1.0:bafybeiaz5auftwxpt4czrmeeesggqlkc2kosmetq6adrebeu6g7bkhqc2u
- eightballer/http_server:0.1.0:bafybeidrvllrr23mc6bvjxn6v3hny6oiwhfgi72n2b7w6ck5luousjfbbq
- eightballer/telegram_wrapper:0.1.0:bafybeib4ncepviza37m7272zacn7i5beohgwe722hkod6p4oz4hhs4kwk4
- zarathustra/openai_api:0.1.0:bafybeicgrjgthj6vva3spg4apy43ptubw47ycfk3phhpfncblf2qnz7qju
contracts: []
protocols:
- zarathustra/llm_chat_completion:1.0.0:bafybeifdp2rwfar5vbs33p56dlin76v62p5fdvspwnpasraunp2wa7gxo4
- eightballer/default:0.1.0:bafybeicsdb3bue2xoopc6lue7njtyt22nehrnkevmkuk2i6ac65w722vwy
- eightballer/http:0.1.0:bafybeid75xhq7hfdt7sgj7yrn44yj57xrgxscaw34ir46tndfzvodioxme
- open_aea/signing:1.0.0:bafybeig2d36zxy65vd7fwhs7scotuktydcarm74aprmrb5nioiymr3yixm
- eightballer/chatroom:0.1.0:bafybeib36ua2o3lea5vkp6erhf23wb4egm6us5xj2z2xd7sq2tjarlzt4i
skills:
- zarathustra/goldman_stacked_abci_app:0.1.0:bafybeibc6lnfmebqkrbbmuoqfifwjqseuhkpyev3v2ua4qkak3dh4vme7e
customs: []
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: true
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  handlers:
    console:
      class: rich.logging.RichHandler
      level: INFO
    logfile:
      class: logging.FileHandler
      filename: log.txt
      formatter: standard
      level: INFO
  loggers:
    aea:
      handlers:
      - console
      - logfile
      level: INFO
      propagate: false
  version: 1
dependencies:
  open-aea-ledger-cosmos: {}
  open-aea-ledger-ethereum: {}
  rich: {}
default_connection: null
---
public_id: zarathustra/openai_api:0.1.0
type: connection
config:
  api_key: ${str:sk-TK0YiafaI1lX61UyT1Ij5g}
  base_url: ${str:https://chatapi.akash.network/api/v1}
---
public_id: eightballer/telegram_wrapper:0.1.0:bafybeic2hcolhlbswi5xsvkmjtqovo2fecxzz2xg3fc7tmyuo2pr3imxnm
type: connection
config:
  target_skill_id: zarathustra/goldman_stacked_abci_app:0.1.0
  token: ${CONNECTION_TELEGRAM_WRAPPER_CONFIG_TOKEN:str:121}
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: zarathustra/goldman_stacked_abci_app:0.1.0
---
public_id: zarathustra/goldman_stacked_abci_app:0.1.0:bafybeic2hcolhlbswi5xsvkmjtqovo2fecxzz2xg3fc7tmyuo2pr3imxnm
type: skill
models:
  agent_persona:
    args:
      persona_name: ${str:'Scam Bankman-Fraud'}
      persona_description: ${str:'A notorious figure in the crypto world, known for
        his controversial actions and influence.'}
  goldman_stacked_strategy:
    args:
      data_dir: ${str:../data}
      output_dir: ${str:../output}
