name: goldman_stacked
author: zarathustra
version: 0.1.0
description: A new service, scaffolded by the Adev cli from zarathustra/goldman_stacked:0.1.0
aea_version: '>=1.0.0, <2.0.0'
license: apache-2.0
fingerprint:
  __init__.py: bafybeie6bz23onmpik76bz56we3vnexnxrgxso3r5xiulxtuq3zvkpf5ea
  tests/__init__.py: bafybeig6wmq5kzol7wkc6rxzjavwylgtkwl7aa6qvep5z4k6loqyg23cbu
  tests/test_service.py: bafybeicsp7vx522wwhz6zjm3m7za5aowp6vluj7tl2g2w4gbzml3otvhaa
fingerprint_ignore_patterns: []
agent: zarathustra/goldman_stacked:0.1.0:bafybeid6jddv2kjh5ahqjdmacbzvjuzu7qeitws7ees4uazvjz5ntdfxci
number_of_agents: 1
deployment:
  agent:
    ports: {}
    volumes: {}
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: zarathustra/goldman_stacked_abci_app:0.1.0
