name: goldman_stacked
author: zarathustra
version: 0.1.0
description: An autonomous collection of agents to act as an immune response to governance
  attacks on DAOs, using a stack of memetic agents to protect the DAO from proposals
  which are not in the best interest of the DAO. Built at ETHPrague 2025.
aea_version: '>=1.0.0, <2.0.0'
license: apache-2.0
fingerprint:
  __init__.py: bafybeifdc5tk6topwmcviejgkm3lmrhnhk6fqqvh76hv7xwg3qkhxifznm
  tests/__init__.py: bafybeiausykbndof27hjfgwqg6nnmk7zw7lyytwzekih3gszwdypbtxjka
  tests/test_service.py: bafybeicplirjoql5q3l5zjl5xrgamnoxuj3year7u2vrtfnzzllzeyutuy
fingerprint_ignore_patterns: []
agent: zarathustra/goldman_stacked:0.1.0:bafybeif4sqtj7oegwm4ciryz4obknegqv3toycm3izmws3xijffnp2brry
number_of_agents: 1
deployment:
  agent:
    ports: {}
    volumes: {}
---
public_id: eightballer/http_server:0.1.0:bafybeicp3ubkonolxjgnwgqmaz624qduwzzz74fbjizu77lyvnpo77uv7u
type: connection
config:
  host: 0.0.0.0
  port: 8888
  target_skill_id: zarathustra/goldman_stacked_abci_app:0.1.0
